import { ReactNode, useReducer, useState } from "react";
import { drawContext } from "../../global/context/drawContext";
import { Tool } from "../../global/enums/drawEnums";
import {
	snapshotReduce,
} from "../../reducers/snapshotReduce";

type DrawProviderTypes = {
	children: ReactNode;
};
export type SnapshotTypes = {
	list: ImageData[];
	listFocus: number;
};

export default function DrawProvider({ children }: DrawProviderTypes) {
	//the current color for brush tool
	const [currentColor , setCurrentColor] = useState("#262626");

	//list of recently used colors
	const [colorHistory , setColorHistory] = useState(["262626"]);

	//the current active tool
	const [currentTool, setCurrentTool] = useState(Tool.Brush);

	//the size of the area affected by the current tool
	const [size , setSize] = useState(1);

	//list of the snpashots generated by each action
	const [snapshot, dispatch] = useReducer(snapshotReduce, {
		list: [],
		listFocus: 0,
	});

	const addSnapshot = (imageData: ImageData) => {
		dispatch({
			type: "add",
			value: imageData,
		});
	};

	const previusSnapshot = () => {
		dispatch({
			type: "previus",
		});
	};
	const advanceSnapshot = () => {
		dispatch({
			type: "advance",
		});
	};

	const addColorToHistory = (newColor : string) => {
		const NEW_LIST = [...new Set([newColor,...colorHistory , ])];
		if(NEW_LIST.length > 14)NEW_LIST.pop();
		setColorHistory(NEW_LIST);
	}

	return (
		<drawContext.Provider
			value={{
				tool: {
					current: currentTool,
					update: setCurrentTool,
				},
				snapshot: {
					current: snapshot.list[snapshot.listFocus],
					add: addSnapshot,
					previus: previusSnapshot,
					advance: advanceSnapshot,
				},
				color : {
					current : currentColor,
					history : colorHistory,
					add : addColorToHistory,
					update : setCurrentColor
				},
				effectSize : {
					current : size,
					update : setSize
				}
			}}
		>
			{children}
		</drawContext.Provider>
	);
}
